//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Botique.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Botique.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _02_5 {
            get {
                object obj = ResourceManager.GetObject("02-5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0afb874b021733a994d122109ca7733a__men_fashion_casual_gentleman_fashion {
            get {
                object obj = ResourceManager.GetObject("0afb874b021733a994d122109ca7733a--men-fashion-casual-gentleman-fashion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0ecfeaf4f18102eaf80204c51c9b56d4 {
            get {
                object obj = ResourceManager.GetObject("0ecfeaf4f18102eaf80204c51c9b56d4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0fa598260b51341bdeaaad0f8f0aec9f {
            get {
                object obj = ResourceManager.GetObject("0fa598260b51341bdeaaad0f8f0aec9f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_0c980448_ca8c_4457_84eb_81ff8cface10_large {
            get {
                object obj = ResourceManager.GetObject("1_0c980448-ca8c-4457-84eb-81ff8cface10_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_0x0 {
            get {
                object obj = ResourceManager.GetObject("1.0x0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_4f2bb7ae_440c_437a_acfa_0d3c358ec496_large {
            get {
                object obj = ResourceManager.GetObject("1_4f2bb7ae-440c-437a-acfa-0d3c358ec496_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_dd8fc76c_f6cb_4a69_83f4_2c9cebeea36a_large {
            get {
                object obj = ResourceManager.GetObject("1_dd8fc76c-f6cb-4a69-83f4-2c9cebeea36a_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_dd8fc76c_f6cb_4a69_83f4_2c9cebeea36a_large1 {
            get {
                object obj = ResourceManager.GetObject("1_dd8fc76c-f6cb-4a69-83f4-2c9cebeea36a_large1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _10_fashion_boutiques {
            get {
                object obj = ResourceManager.GetObject("10-fashion-boutiques", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _101 {
            get {
                object obj = ResourceManager.GetObject("101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _123bf7c815990b5f6d3304e247f1cbfe {
            get {
                object obj = ResourceManager.GetObject("123bf7c815990b5f6d3304e247f1cbfe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _13892187_1326669984040350_7565637278338882334_n {
            get {
                object obj = ResourceManager.GetObject("13892187_1326669984040350_7565637278338882334_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_6_year_old_baby_girl_set_summer_style_cute_tutu_dress_headband_designer_Polka_Dot {
            get {
                object obj = ResourceManager.GetObject("2-6-year-old-baby-girl-set-summer-style-cute-tutu-dress-headband-designer-Polka-D" +
                        "ot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2016_new_brand_double_pcs_men_suit_vest_waistcoat_men_casual_good_quality_sleeveless_slim_fit_jpg_220x220 {
            get {
                object obj = ResourceManager.GetObject("2016-new-brand-double-pcs-men-suit-vest-waistcoat-men-casual-good-quality-sleevel" +
                        "ess-slim-fit.jpg_220x220", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2016_new_brand_double_pcs_men_suit_vest_waistcoat_men_casual_good_quality_sleeveless_slim_fit1 {
            get {
                object obj = ResourceManager.GetObject("2016-new-brand-double-pcs-men-suit-vest-waistcoat-men-casual-good-quality-sleevel" +
                        "ess-slim-fit1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2016_Two_Pieces_font_b_Pakistani_b_font_font_b_Dresses_b_font_Green_Bling_Sequins {
            get {
                object obj = ResourceManager.GetObject("2016-Two-Pieces-font-b-Pakistani-b-font-font-b-Dresses-b-font-Green-Bling-Sequins" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2016_Two_Pieces_font_b_Pakistani_b_font_font_b_Dresses_b_font_Green_Bling_Sequins__1_ {
            get {
                object obj = ResourceManager.GetObject("2016-Two-Pieces-font-b-Pakistani-b-font-font-b-Dresses-b-font-Green-Bling-Sequins" +
                        " (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2016_Two_Pieces_font_b_Pakistani_b_font_font_b_Dresses_b_font_Green_Bling_Sequins1 {
            get {
                object obj = ResourceManager.GetObject("2016-Two-Pieces-font-b-Pakistani-b-font-font-b-Dresses-b-font-Green-Bling-Sequins" +
                        "1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017_Muchachas_Del_Verano_de_la_Ropa_de_Los_Cabritos_Determinados_Conjuntos_de_Ropa_de_Beb_eacute {
            get {
                object obj = ResourceManager.GetObject("2017-Muchachas-Del-Verano-de-la-Ropa-de-Los-Cabritos-Determinados-Conjuntos-de-Ro" +
                        "pa-de-Beb&eacute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017_New_font_b_Kids_b_font_Clothing_Sets_T_shirt_Short_font_b_Pants_b {
            get {
                object obj = ResourceManager.GetObject("2017-New-font-b-Kids-b-font-Clothing-Sets-T-shirt-Short-font-b-Pants-b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017_new_korea_fashion_brand_men_clothes {
            get {
                object obj = ResourceManager.GetObject("2017-new-korea-fashion-brand-men-clothes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017_new_summer_dress_children_font_b_designer_b_font_font_b_kids_b_font_clothes {
            get {
                object obj = ResourceManager.GetObject("2017-new-summer-dress-children-font-b-designer-b-font-font-b-kids-b-font-clothes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017_new_summer_style_fashion_100_Cotton_brand_stars_Baby_boy_t_shirt_with_half_pants {
            get {
                object obj = ResourceManager.GetObject("2017-new-summer-style-fashion-100-Cotton-brand-stars-Baby-boy-t-shirt-with-half-p" +
                        "ants", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017_New_Summer_Style_font_b_Baby_b_font_Girl_Pants_font_b_Baby_b_font {
            get {
                object obj = ResourceManager.GetObject("2017-New-Summer-Style-font-b-Baby-b-font-Girl-Pants-font-b-Baby-b-font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017_New_Trend_False_Two_Fashion_Casual_Men_Shirt_Long_Sleeve_Slim_Fit_Shirt_Men_Print_jpg_640x640 {
            get {
                object obj = ResourceManager.GetObject("2017-New-Trend-False-Two-Fashion-Casual-Men-Shirt-Long-Sleeve-Slim-Fit-Shirt-Men-" +
                        "Print.jpg_640x640", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017_summer_style_fashion_black_birds_print_font_b_Baby_b_font_boys_brand_t_shirt {
            get {
                object obj = ResourceManager.GetObject("2017-summer-style-fashion-black-birds-print-font-b-Baby-b-font-boys-brand-t-shirt" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017_جديد_الصيف_نمط_أزياء_الطباعة_طفل_الفتيان_brand_القمصان_و_الحريم_السراويل_فتاة_الملابس_الرياضية {
            get {
                object obj = ResourceManager.GetObject("2017-جديد-الصيف-نمط-أزياء-الطباعة-طفل-الفتيان-brand-القمصان-و-الحريم-السراويل-فتا" +
                        "ة-الملابس-الرياضية", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017_جديد_الصيف_نمط_أزياء_الطباعة_طفل_الفتيان_brand_القمصان_و_الحريم_السراويل_فتاة_الملابس_الرياضية1 {
            get {
                object obj = ResourceManager.GetObject("2017-جديد-الصيف-نمط-أزياء-الطباعة-طفل-الفتيان-brand-القمصان-و-الحريم-السراويل-فتا" +
                        "ة-الملابس-الرياضية1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2017girl_baby_clothes_summer_brand_design_denim_tutu_princess_party_dress_for_infant_baby_clothing_sleeveless {
            get {
                object obj = ResourceManager.GetObject("2017girl-baby-clothes-summer-brand-design-denim-tutu-princess-party-dress-for-inf" +
                        "ant-baby-clothing-sleeveless", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _24a2e1d0706719d5d9871fadba231af5 {
            get {
                object obj = ResourceManager.GetObject("24a2e1d0706719d5d9871fadba231af5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _25_IMG_8571 {
            get {
                object obj = ResourceManager.GetObject("25-IMG_8571", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32395307521083ffed8e1a57c3795264 {
            get {
                object obj = ResourceManager.GetObject("32395307521083ffed8e1a57c3795264", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_latest_classy_kurta_style_men_dress {
            get {
                object obj = ResourceManager.GetObject("4-latest-classy-kurta-style-men-dress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4603f492a56a4a31d894b602b9622973__online_wedding_dresses_indian_wedding_dresses {
            get {
                object obj = ResourceManager.GetObject("4603f492a56a4a31d894b602b9622973--online-wedding-dresses-indian-wedding-dresses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4603f492a56a4a31d894b602b9622973__online_wedding_dresses_indian_wedding_dresses1 {
            get {
                object obj = ResourceManager.GetObject("4603f492a56a4a31d894b602b9622973--online-wedding-dresses-indian-wedding-dresses1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4c7b2f70a52c7cd6a3c90eed380398af {
            get {
                object obj = ResourceManager.GetObject("4c7b2f70a52c7cd6a3c90eed380398af", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4c7b2f70a52c7cd6a3c90eed380398af1 {
            get {
                object obj = ResourceManager.GetObject("4c7b2f70a52c7cd6a3c90eed380398af1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4e262c7abccce81a0c3b350ece719325 {
            get {
                object obj = ResourceManager.GetObject("4e262c7abccce81a0c3b350ece719325", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _57dcf0e98eda02cf0eedcc395b6d2c17 {
            get {
                object obj = ResourceManager.GetObject("57dcf0e98eda02cf0eedcc395b6d2c17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5a237e1cc7113526ab986b866bf22bd1 {
            get {
                object obj = ResourceManager.GetObject("5a237e1cc7113526ab986b866bf22bd1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5aa3e4728a3cd7e568f8f446d6a1eb09__moda_kids_boy_outfits {
            get {
                object obj = ResourceManager.GetObject("5aa3e4728a3cd7e568f8f446d6a1eb09--moda-kids-boy-outfits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5aba4867201f8b980acbed22ca600f98 {
            get {
                object obj = ResourceManager.GetObject("5aba4867201f8b980acbed22ca600f98", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5aba4867201f8b980acbed22ca600f981 {
            get {
                object obj = ResourceManager.GetObject("5aba4867201f8b980acbed22ca600f981", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _687f19a8b5e0df619765aa0afe5b9ae3 {
            get {
                object obj = ResourceManager.GetObject("687f19a8b5e0df619765aa0afe5b9ae3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _738d75db1ee0cd6b6702c96116f3dc75__clothing_ideas_maxi {
            get {
                object obj = ResourceManager.GetObject("738d75db1ee0cd6b6702c96116f3dc75--clothing-ideas-maxi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _738d75db1ee0cd6b6702c96116f3dc75__clothing_ideas_maxi1 {
            get {
                object obj = ResourceManager.GetObject("738d75db1ee0cd6b6702c96116f3dc75--clothing-ideas-maxi1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _738d75db1ee0cd6b6702c96116f3dc75__clothing_ideas_maxi2 {
            get {
                object obj = ResourceManager.GetObject("738d75db1ee0cd6b6702c96116f3dc75--clothing-ideas-maxi2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7887c9816cfa7bd65b722deb75d6f7f8__baby_boy_fashion_kids_fashion {
            get {
                object obj = ResourceManager.GetObject("7887c9816cfa7bd65b722deb75d6f7f8--baby-boy-fashion-kids-fashion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7a0dcc38c57d7746e456c1c6af88b735 {
            get {
                object obj = ResourceManager.GetObject("7a0dcc38c57d7746e456c1c6af88b735", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7e828dc619e373126485e8982455bd78 {
            get {
                object obj = ResourceManager.GetObject("7e828dc619e373126485e8982455bd78", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7e828dc619e373126485e8982455bd781 {
            get {
                object obj = ResourceManager.GetObject("7e828dc619e373126485e8982455bd781", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7eb05ab0663e89a8b4f14ab67727f763 {
            get {
                object obj = ResourceManager.GetObject("7eb05ab0663e89a8b4f14ab67727f763", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8d4a1eab2017cc89944e2d007b98ed66__pakistani_dress_design_pakistani_dresses {
            get {
                object obj = ResourceManager.GetObject("8d4a1eab2017cc89944e2d007b98ed66--pakistani-dress-design-pakistani-dresses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _93aa74c5a2377fb119a8b17ca25393b6 {
            get {
                object obj = ResourceManager.GetObject("93aa74c5a2377fb119a8b17ca25393b6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a5a5796d70298db1bdd3198942878f7c {
            get {
                object obj = ResourceManager.GetObject("a5a5796d70298db1bdd3198942878f7c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a99e16328a556f08b263c47da56c3c92 {
            get {
                object obj = ResourceManager.GetObject("a99e16328a556f08b263c47da56c3c92", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ABC_Fabrics_6555_1_weddingplz {
            get {
                object obj = ResourceManager.GetObject("ABC-Fabrics-6555-1-weddingplz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ABC_Fabrics_6555_1_weddingplz1 {
            get {
                object obj = ResourceManager.GetObject("ABC-Fabrics-6555-1-weddingplz1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ABC_Fabrics_6555_1_weddingplz2 {
            get {
                object obj = ResourceManager.GetObject("ABC-Fabrics-6555-1-weddingplz2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap admirable_art_silk_kurta_500x500 {
            get {
                object obj = ResourceManager.GetObject("admirable-art-silk-kurta-500x500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap af84187bafc4d9884ae8b5c1d429dd09__bridal_lehenga_lehenga_choli {
            get {
                object obj = ResourceManager.GetObject("af84187bafc4d9884ae8b5c1d429dd09--bridal-lehenga-lehenga-choli", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap afe9c562ae80740ce42c23e51627a909 {
            get {
                object obj = ResourceManager.GetObject("afe9c562ae80740ce42c23e51627a909", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap afe9c562ae80740ce42c23e51627a9091 {
            get {
                object obj = ResourceManager.GetObject("afe9c562ae80740ce42c23e51627a9091", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Anarkali_Stylish_Red_Frocks_for_Wedding_Bridals_2016_7 {
            get {
                object obj = ResourceManager.GetObject("Anarkali-Stylish-Red-Frocks-for-Wedding-Bridals-2016-7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Asim_Jofa_Formal_Wear_Luxury_pret_2017_2018_Dresses_design_Collection_1 {
            get {
                object obj = ResourceManager.GetObject("Asim-Jofa-Formal-Wear-Luxury-pret-2017-2018-Dresses-design-Collection-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Asim_Jofa_Formal_Wear_Luxury_pret_2017_2018_Dresses_design_Collection_11 {
            get {
                object obj = ResourceManager.GetObject("Asim-Jofa-Formal-Wear-Luxury-pret-2017-2018-Dresses-design-Collection-11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap attractive_design_big_girls_dress_fashion {
            get {
                object obj = ResourceManager.GetObject("attractive-design-big-girls-dress-fashion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap b7cnb87cvb_dress_design_salwar_kameez_1 {
            get {
                object obj = ResourceManager.GetObject("b7cnb87cvb-dress-design-salwar-kameez-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ba6a31275b0d06501138f8e6871a6130 {
            get {
                object obj = ResourceManager.GetObject("ba6a31275b0d06501138f8e6871a6130", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Baby_Boy_Clothing_Set_Summer_2017_New_Cotton_Children_Summer_Boys_font_b_Clothes_b_font {
            get {
                object obj = ResourceManager.GetObject("Baby-Boy-Clothing-Set-Summer-2017-New-Cotton-Children-Summer-Boys-font-b-Clothes-" +
                        "b-font", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap baby_clothes_2016_new_design_baby_girl_boutique {
            get {
                object obj = ResourceManager.GetObject("baby-clothes-2016-new-design-baby-girl-boutique", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bleiser_masculino_blaser_Partido_Del_Vestido_de_Boda_Chaquetas_font_b_Blazers_b_font_Traje_Chaqueta {
            get {
                object obj = ResourceManager.GetObject("Bleiser-masculino-blaser-Partido-Del-Vestido-de-Boda-Chaquetas-font-b-Blazers-b-f" +
                        "ont-Traje-Chaqueta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blue_And_Light_Brown_Back_Trail_Maxi_for_Party_Wear {
            get {
                object obj = ResourceManager.GetObject("Blue-And-Light-Brown-Back-Trail-Maxi-for-Party-Wear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bridal_maxi_dress_walima_2014__6_ {
            get {
                object obj = ResourceManager.GetObject("bridal-maxi-dress-walima-2014 (6)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CL_211A_2_large {
            get {
                object obj = ResourceManager.GetObject("CL-211A_2_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cosmetics_employee {
            get {
                object obj = ResourceManager.GetObject("cosmetics-employee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap d79660b750cabeb0100e2470ec26ae37 {
            get {
                object obj = ResourceManager.GetObject("d79660b750cabeb0100e2470ec26ae37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dans_la_caverne_aux_merveilles_de_Zuhair_Murad {
            get {
                object obj = ResourceManager.GetObject("Dans-la-caverne-aux-merveilles-de-Zuhair-Murad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dazzling_Cute_kids_wear_party_function_frocks_designs_2017_1 {
            get {
                object obj = ResourceManager.GetObject("Dazzling-Cute-kids-wear-party-function-frocks-designs-2017-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dependienta {
            get {
                object obj = ResourceManager.GetObject("dependienta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap design_no___7015_front {
            get {
                object obj = ResourceManager.GetObject("design-no---7015_front", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap designer_kurta_suits_250x250 {
            get {
                object obj = ResourceManager.GetObject("designer-kurta-suits-250x250", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__1_ {
            get {
                object obj = ResourceManager.GetObject("download (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__1_1 {
            get {
                object obj = ResourceManager.GetObject("download (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__2_ {
            get {
                object obj = ResourceManager.GetObject("download (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__3_ {
            get {
                object obj = ResourceManager.GetObject("download (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download1 {
            get {
                object obj = ResourceManager.GetObject("download1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download2 {
            get {
                object obj = ResourceManager.GetObject("download2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap drophilla_world_blue_georgette_special_occasion_dre_original {
            get {
                object obj = ResourceManager.GetObject("drophilla-world-blue-georgette-special-occasion-dre-original", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap drophilla_world_blue_georgette_special_occasion_dre_original1 {
            get {
                object obj = ResourceManager.GetObject("drophilla-world-blue-georgette-special-occasion-dre-original1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap e3aa68a972de9ec4f1ebe63a0f09291e {
            get {
                object obj = ResourceManager.GetObject("e3aa68a972de9ec4f1ebe63a0f09291e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f7116ad6c0c325f2f9f72cf7f81c393e {
            get {
                object obj = ResourceManager.GetObject("f7116ad6c0c325f2f9f72cf7f81c393e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fancy_Dresses_latest_Designs_2016 {
            get {
                object obj = ResourceManager.GetObject("Fancy-Dresses-latest-Designs-2016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fancy_Dresses_latest_Designs_20161 {
            get {
                object obj = ResourceManager.GetObject("Fancy-Dresses-latest-Designs-20161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fancy_Indian_Asian_Anarkali_Umbrella_Frocks {
            get {
                object obj = ResourceManager.GetObject("Fancy-Indian-Asian-Anarkali-Umbrella-Frocks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fancy_Indian_Asian_Anarkali_Umbrella_Frocks1 {
            get {
                object obj = ResourceManager.GetObject("Fancy-Indian-Asian-Anarkali-Umbrella-Frocks1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fancy_Indian_Asian_Anarkali_Umbrella_Frocks2 {
            get {
                object obj = ResourceManager.GetObject("Fancy-Indian-Asian-Anarkali-Umbrella-Frocks2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fashion_Boutique_by_KNQ_Associates_Singapore {
            get {
                object obj = ResourceManager.GetObject("Fashion-Boutique-by-KNQ-Associates-Singapore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hermes_store_mumbai {
            get {
                object obj = ResourceManager.GetObject("hermes_store_mumbai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HTB1c5jgKVXXXXawaXXXq6xXFXXXD {
            get {
                object obj = ResourceManager.GetObject("HTB1c5jgKVXXXXawaXXXq6xXFXXXD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i7534491777b1aa8b5b32c2e8666dbe1a495 {
            get {
                object obj = ResourceManager.GetObject("i7534491777b1aa8b5b32c2e8666dbe1a495", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__1_ {
            get {
                object obj = ResourceManager.GetObject("images (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__10_ {
            get {
                object obj = ResourceManager.GetObject("images (10)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__12_ {
            get {
                object obj = ResourceManager.GetObject("images (12)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__13_ {
            get {
                object obj = ResourceManager.GetObject("images (13)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__15_ {
            get {
                object obj = ResourceManager.GetObject("images (15)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__16_ {
            get {
                object obj = ResourceManager.GetObject("images (16)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__2_ {
            get {
                object obj = ResourceManager.GetObject("images (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__22_ {
            get {
                object obj = ResourceManager.GetObject("images (22)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__26_ {
            get {
                object obj = ResourceManager.GetObject("images (26)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__3_ {
            get {
                object obj = ResourceManager.GetObject("images (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__5_ {
            get {
                object obj = ResourceManager.GetObject("images (5)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__5_1 {
            get {
                object obj = ResourceManager.GetObject("images (5)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__6_ {
            get {
                object obj = ResourceManager.GetObject("images (6)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__6_1 {
            get {
                object obj = ResourceManager.GetObject("images (6)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__9_ {
            get {
                object obj = ResourceManager.GetObject("images (9)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images1 {
            get {
                object obj = ResourceManager.GetObject("images1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istanbul_turkey_employees_at_the_boutique_of_bahar_korcan_d2tjkx {
            get {
                object obj = ResourceManager.GetObject("istanbul-turkey-employees-at-the-boutique-of-bahar-korcan-d2tjkx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap J_couture_Junaid_Jamshed_Men_Sherwanis_Collection_for_Weddings_Paries_2015_2016_9 {
            get {
                object obj = ResourceManager.GetObject("J.couture-Junaid-Jamshed-Men-Sherwanis-Collection-for-Weddings-Paries-2015-2016-9" +
                        "", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap J1 {
            get {
                object obj = ResourceManager.GetObject("J1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap l {
            get {
                object obj = ResourceManager.GetObject("l", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Latest_Pakistani_Party_Wear_Winter_Dresses_Collection {
            get {
                object obj = ResourceManager.GetObject("Latest-Pakistani-Party-Wear-Winter-Dresses-Collection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Latest_Party_Wear_Frocks_dresses_2015_2016 {
            get {
                object obj = ResourceManager.GetObject("Latest-Party-Wear-Frocks-dresses-2015-2016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap luxurysociety_1844265_5 {
            get {
                object obj = ResourceManager.GetObject("luxurysociety_1844265_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap luxxe_box_store_image {
            get {
                object obj = ResourceManager.GetObject("luxxe_box_store_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p_NeonDragonfly_boutique_Reno_59_330x220 {
            get {
                object obj = ResourceManager.GetObject("p-NeonDragonfly-boutique-Reno_59_330x220", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PIA {
            get {
                object obj = ResourceManager.GetObject("PIA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rabiya_boutique___1_ {
            get {
                object obj = ResourceManager.GetObject("rabiya boutique  (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rabiya_boutique___1_1 {
            get {
                object obj = ResourceManager.GetObject("rabiya boutique  (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rBVaJFjIvSiAAt7jAADNpNMijd8629 {
            get {
                object obj = ResourceManager.GetObject("rBVaJFjIvSiAAt7jAADNpNMijd8629", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap retail_employee_research_report {
            get {
                object obj = ResourceManager.GetObject("retail-employee-research-report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Schaufenster {
            get {
                object obj = ResourceManager.GetObject("Schaufenster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Spring_Dresses_For_Girls_l9lyZs {
            get {
                object obj = ResourceManager.GetObject("Spring-Dresses-For-Girls-l9lyZs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sri_sai_designer_boutique_miyapur_hyderabad_cvg5k {
            get {
                object obj = ResourceManager.GetObject("sri-sai-designer-boutique-miyapur-hyderabad-cvg5k", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sri_sai_designer_boutique_miyapur_hyderabad_cvg5k1 {
            get {
                object obj = ResourceManager.GetObject("sri-sai-designer-boutique-miyapur-hyderabad-cvg5k1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap store_display_window_light_decorative_bike_fashion_boutique_display_window_mannequins_store_sale_window_front_shop_47074317 {
            get {
                object obj = ResourceManager.GetObject("store-display-window-light-decorative-bike-fashion-boutique-display-window-manneq" +
                        "uins-store-sale-window-front-shop-47074317", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap store_display_window_light_decorative_bike_fashion_boutique_display_window_mannequins_store_sale_window_front_shop_470743171 {
            get {
                object obj = ResourceManager.GetObject("store-display-window-light-decorative-bike-fashion-boutique-display-window-manneq" +
                        "uins-store-sale-window-front-shop-470743171", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap store_display_window_light_decorative_bike_fashion_boutique_display_window_mannequins_store_sale_window_front_shop_470743172 {
            get {
                object obj = ResourceManager.GetObject("store-display-window-light-decorative-bike-fashion-boutique-display-window-manneq" +
                        "uins-store-sale-window-front-shop-470743172", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unnamed {
            get {
                object obj = ResourceManager.GetObject("unnamed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unnamed1 {
            get {
                object obj = ResourceManager.GetObject("unnamed1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zl17012 {
            get {
                object obj = ResourceManager.GetObject("zl17012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Платье_а_силуэта_фото_модные_тенденции_2016_2017_1 {
            get {
                object obj = ResourceManager.GetObject("Платье-а-силуэта-фото-модные-тенденции-2016-2017-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
